SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS fofocas_rapidas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(220) NOT NULL,
    subtitulo VARCHAR(500) NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    publicado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_fofocas_publicacao (ativo, publicado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
